version: '3'
services:
  dbt:
    container_name: dbtapp
    restart: unless-stopped
    build:
        context: .
        dockerfile: Dockerfile

networks:
  default:
    external: true
    name: proxies
