# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "058d5a48f3e4f6a52883ae4bb97a99e9"
name = "discount-by-tags-remix"
application_url = "https://dividend-cart-webcams-use.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "j-montano-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://dividend-cart-webcams-use.trycloudflare.com/auth/callback",
  "https://dividend-cart-webcams-use.trycloudflare.com/auth/shopify/callback",
  "https://dividend-cart-webcams-use.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
